// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs6_9dHEVXO8S_YneF18iAYbPY45Mb7Qc',
    appId: '1:881212641417:web:a414c0dc12de81bacdb658',
    messagingSenderId: '881212641417',
    projectId: 'fanny-771de',
    authDomain: 'fanny-771de.firebaseapp.com',
    storageBucket: 'fanny-771de.firebasestorage.app',
    measurementId: 'G-H46X9MQKW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOigDJJUf1R_zje1Nagclgyc531N4Y1c',
    appId: '1:881212641417:android:8702ca994daea446cdb658',
    messagingSenderId: '881212641417',
    projectId: 'fanny-771de',
    storageBucket: 'fanny-771de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYLB3PkgoTwdM6W8kilaEzpVhSXHnqfWw',
    appId: '1:881212641417:ios:2da2b0d992feee78cdb658',
    messagingSenderId: '881212641417',
    projectId: 'fanny-771de',
    storageBucket: 'fanny-771de.firebasestorage.app',
    androidClientId: '881212641417-q8pv27i5s0sc3ljeoondg60eo7a6n1ka.apps.googleusercontent.com',
    iosClientId: '881212641417-g7hn61ebdr29u5n5t6p7orpnvm9mgvhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.finny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYLB3PkgoTwdM6W8kilaEzpVhSXHnqfWw',
    appId: '1:881212641417:ios:2da2b0d992feee78cdb658',
    messagingSenderId: '881212641417',
    projectId: 'fanny-771de',
    storageBucket: 'fanny-771de.firebasestorage.app',
    androidClientId: '881212641417-q8pv27i5s0sc3ljeoondg60eo7a6n1ka.apps.googleusercontent.com',
    iosClientId: '881212641417-g7hn61ebdr29u5n5t6p7orpnvm9mgvhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.finny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs6_9dHEVXO8S_YneF18iAYbPY45Mb7Qc',
    appId: '1:881212641417:web:7bc7797eb1b8eeaacdb658',
    messagingSenderId: '881212641417',
    projectId: 'fanny-771de',
    authDomain: 'fanny-771de.firebaseapp.com',
    storageBucket: 'fanny-771de.firebasestorage.app',
    measurementId: 'G-K7HZ7HH36G',
  );

}