name: Flutter iOS Build

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable iOS
        run: flutter config --enable-ios

      - name: Install dependencies
        run: flutter pub get

      # 🔥 أهم خطوة (حل مشكلة Firebase / Pods)
      - name: Fix iOS deployment target for Pods
        run: |
          sed -i '' 's/platform :ios, .*/platform :ios, "15.0"/g' ios/Podfile

      - name: Install CocoaPods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install

      - name: Build iOS (no signing)
        run: flutter build ios --release --no-codesign
